import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import HeaderPage from "./components/Header";
import Marquee from "./components/Marquee";
import Footer from "./components/Footer";
import { ToastContainer } from "react-toastify";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});


export const metadata: Metadata = {
  title: "Bangla News 24",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en" 
      data-theme="light"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full mx-auto flex flex-col">
        <HeaderPage />
         <Marquee />
        <main className="max-w-7xl mx-auto">{children}</main>


        <Footer />
        <ToastContainer />
        </body>
    </html>
  );
}
